### ISSUE TITLE
Consider Vendoring Dependencies

### ISSUE THREAD

**Issue by idiamond-stripe** [coinbase/protoc-gen-rbi#11]
We have a build system that builds `protoc-gen-rbi` as part of a larger repository build by effectively downloading `protoc-gen-rbi` and then running `go build`. This has the effect of downloading all dependencies at build time, which can be slow or flaky given the number of builds we run and Github's potential for rate limiting.

Would you consider taking a PR that checks in the vendor directory with `go mod vendor`? This would enable us to run reproducible builds without depending on the entire world.

This does have the downside that we'd pin to specific repository versions of dependencies, but I think from a dependency standpoint, this is nicer than depending on the builder to fetch the versions at compile time.

If this sounds reasonable, I'm happy to submit a PR to this effect!

cc @praboud-stripe

**Comment by mdehoog** [comment]
@idiamond-stripe sure, happy to accept a PR to vendor deps 👍
